const actionTypes={
    personActions:{
        GET_PERSONS_START:"GET_PERSONS_START",
        GET_PERSONS_SUCCESS:"GET_PERSONS_SUCCESS",
        GET_PERSONS_FAIL:"GET_PERSONS_FAIL",
        DELETE_PERSON_START:"DELETE_PERSON_START",
        DELETE_PERSON_SUCCESS:"DELETE_PERSON_SUCCESS",
        DELETE_PERSON_FAIL:"DELETE_PERSON_FAIL",
        EDIT_PERSON_START:" EDIT_PERSON_START",
        EDIT_PERSON_SUCCESS:" EDIT_PERSON_SUCCESS",
        EDIT_PERSON_FAIL:" EDIT_PERSON_FAIL",
        ADD_PERSON:"ADD_PERSON"
    }
}

export default actionTypes